apiVersion: v1
kind: Endpoints
metadata:
  name: glusterfs-cluster
subsets:
  - addresses:
      - ip: 192.168.59.103  # Replace with the actual IP of your Minikube node
    ports:
      - port: 24007
