apiVersion: v1
kind: Pod
metadata:
  name: mapreduce-worker
spec:
  containers:
  - name: worker
    image: your-mapreduce-worker-image
    volumeMounts:
    - name: nfs-storage
      mountPath: "/data"
  volumes:
  - name: nfs-storage
    persistentVolumeClaim:
      claimName: nfs-pvc
