apiVersion: v1
kind: Pod
metadata:
  name: nfs-test-pod
spec:
  containers:
  - name: nfs-test-container
    image: busybox
    command: ['sh', '-c', 'echo Hello Kubernetes! > /mnt/data/hello.txt && cat /mnt/data/hello.txt && sleep 3600']
    volumeMounts:
    - name: nfs-volume
      mountPath: /mnt/data
  volumes:
  - name: nfs-volume
    persistentVolumeClaim:
      claimName: nfs-pvc
