apiVersion: v1
kind: ServiceAccount
metadata:
  name: flask-app-sa
  namespace: default

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: flask-app-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "create", "delete"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: flask-app-rolebinding
  namespace: default
subjects:
- kind: ServiceAccount
  name: flask-app-sa
  namespace: default
roleRef:
  kind: Role
  name: flask-app-role
  apiGroup: rbac.authorization.k8s.io