apiVersion: batch/v1
kind: Job
metadata:
  name: mapreduce-mapper
  namespace: sad
spec:
  template:
    metadata:
      labels:
        app: mapreduce-mapper
    spec:
      containers:
      - name: mapper
        image: dkeramidas1/worker_node:v01
        env:
          - name: MODE
            value: "mapper"
          - name: ZOOKEEPER_HOST
            value: "zk-cs.sad.svc.cluster.local:2181"
          - name: NAMESPACE
            value: "sad"
          - name: NODE_ID
            value: "unique-mapper-id"
        imagePullPolicy: Always
      restartPolicy: OnFailure
