#nfs-pv.yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain  # This line changes the reclaim policy
  nfs:
    path: /exports
    server: nfs-server.default.svc.cluster.local

